.TH al_detach_sample_instance 3 "" "Allegro reference manual"
.SH NAME
.PP
al_detach_sample_instance
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

bool\ al_detach_sample_instance(ALLEGRO_SAMPLE_INSTANCE\ *spl)
\f[]
.fi
.SH DESCRIPTION
.PP
Detach the sample instance from whatever it's attached to, if
anything.
.PP
Returns true on success.
