.TH al_get_channel_count 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_channel_count
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>
\f[]
.fi
.SH DESCRIPTION
.PP
Return the number of channels for the given channel configuration,
which is one of the values listed under ALLEGRO_CHANNEL_CONF(3).
