.TH al_get_audio_stream_position_secs 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_audio_stream_position_secs
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

double\ al_get_audio_stream_position_secs(ALLEGRO_AUDIO_STREAM\ *stream)
\f[]
.fi
.SH DESCRIPTION
.PP
Return the position of the stream in seconds.
Currently this can only be called on streams created with
al_load_audio_stream(3).
