.TH al_get_sample_instance_attached 3 "" "Allegro reference manual"
.SH NAME
.PP
al_get_sample_instance_attached
.SH SYNOPSIS
.IP
.nf
\f[C]
#include\ <allegro5/allegro_audio.h>

bool\ al_get_sample_instance_attached(const\ ALLEGRO_SAMPLE_INSTANCE\ *spl)
\f[]
.fi
.SH DESCRIPTION
.PP
Return whether the sample instance is attached to something.
